# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
# 1. Import FirefoxOptions
from selenium.webdriver.firefox.options import Options

class TestSmokeTest():
  def setup_method(self, method):
    # 2. Create an Options object
    options = Options()
    # 3. Add the headless argument
    options.add_argument("-headless")
    # 4. Pass the options when creating the driver
    self.driver = webdriver.Firefox(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_1Navigatetothehomepage(self):
    self.driver.get("http://localhost:5500/cse270-teton/teton/1.6/")
    self.driver.set_window_size(785, 822)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_2Navigatetothehomepage(self):
    self.driver.get("http://localhost:5500/cse270-teton/teton/1.6/")
    self.driver.set_window_size(1550, 830)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us").click()
  
  def test_3Navigatetothedirectorypage(self):
    self.driver.get("http://localhost:5500/cse270-teton/teton/1.6/directory.html")
    self.driver.set_window_size(781, 822)
    self.driver.find_element(By.ID, "directory-grid").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
    self.driver.find_element(By.ID, "directory-list").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)").text == "Teton Turf and Tree"
  
  def test_4Navigatetothejoinpage(self):
    self.driver.get("http://localhost:5500/cse270-teton/teton/1.6/join.html")
    self.driver.set_window_size(781, 822)
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "fname").send_keys("Daijiro")
    self.driver.find_element(By.NAME, "lname").send_keys("Sagane")
    self.driver.find_element(By.NAME, "bizname").send_keys("Sagane Enginering")
    self.driver.find_element(By.NAME, "biztitle").send_keys("CEO")
    self.driver.find_element(By.NAME, "submit").click()
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
  
  def test_5Navigatetotheadminpage(self):
    self.driver.get("http://localhost:5500/cse270-teton/teton/1.6/admin.html")
    self.driver.set_window_size(781, 822)
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".errorMessage").text == "Invalid username and password."
  
